[2023-08-02T09:29:21.843+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: toronto_real_estate_etl.ToStageTable manual__2023-08-02T09:24:16.653874+00:00 [queued]>
[2023-08-02T09:29:21.850+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: toronto_real_estate_etl.ToStageTable manual__2023-08-02T09:24:16.653874+00:00 [queued]>
[2023-08-02T09:29:21.850+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-02T09:29:21.859+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): ToStageTable> on 2023-08-02 09:24:16.653874+00:00
[2023-08-02T09:29:21.863+0000] {standard_task_runner.py:57} INFO - Started process 378 to run task
[2023-08-02T09:29:21.866+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'toronto_real_estate_etl', 'ToStageTable', 'manual__2023-08-02T09:24:16.653874+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp766lt4xy']
[2023-08-02T09:29:21.868+0000] {standard_task_runner.py:85} INFO - Job 91: Subtask ToStageTable
[2023-08-02T09:29:21.901+0000] {task_command.py:410} INFO - Running <TaskInstance: toronto_real_estate_etl.ToStageTable manual__2023-08-02T09:24:16.653874+00:00 [running]> on host e5187b3c4256
[2023-08-02T09:29:21.950+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='toronto_real_estate_etl' AIRFLOW_CTX_TASK_ID='ToStageTable' AIRFLOW_CTX_EXECUTION_DATE='2023-08-02T09:24:16.653874+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-02T09:24:16.653874+00:00'
[2023-08-02T09:29:25.511+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/main.py", line 100, in insertIntoStage
    load(filepath)
  File "/opt/airflow/dags/src/Load.py", line 150, in load
    L.loadValues(filename=filename)
  File "/opt/airflow/dags/src/Load.py", line 128, in loadValues
    execute_values(cursor, query, values)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type double precision: "5+"

[2023-08-02T09:29:25.519+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=toronto_real_estate_etl, task_id=ToStageTable, execution_date=20230802T092416, start_date=20230802T092921, end_date=20230802T092925
[2023-08-02T09:29:25.528+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 91 for task ToStageTable (invalid input syntax for type double precision: "5+"
; 378)
[2023-08-02T09:29:25.535+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-02T09:29:25.554+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
