[2023-07-28T14:02:48.188+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: toronto_real_estate_etl.Extract manual__2023-07-28T14:02:46.844954+00:00 [queued]>
[2023-07-28T14:02:48.195+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: toronto_real_estate_etl.Extract manual__2023-07-28T14:02:46.844954+00:00 [queued]>
[2023-07-28T14:02:48.195+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-28T14:02:48.205+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): Extract> on 2023-07-28 14:02:46.844954+00:00
[2023-07-28T14:02:48.209+0000] {standard_task_runner.py:57} INFO - Started process 5616 to run task
[2023-07-28T14:02:48.212+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'toronto_real_estate_etl', 'Extract', 'manual__2023-07-28T14:02:46.844954+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpwmigfb0r']
[2023-07-28T14:02:48.214+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask Extract
[2023-07-28T14:02:48.248+0000] {task_command.py:410} INFO - Running <TaskInstance: toronto_real_estate_etl.Extract manual__2023-07-28T14:02:46.844954+00:00 [running]> on host 7d0ee807347f
[2023-07-28T14:02:48.302+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='toronto_real_estate_etl' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2023-07-28T14:02:46.844954+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-28T14:02:46.844954+00:00'
[2023-07-28T14:02:48.303+0000] {main.py:30} INFO - https://www.kijiji.ca/b-apartments-condos/page-1/c37l1700273
[2023-07-28T14:06:53.577+0000] {logging_mixin.py:150} INFO - data/result_page_number_1_2023-07-28.json
[2023-07-28T14:06:53.578+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/main.py", line 71, in extract
    e.getListings(2)
  File "/opt/airflow/dags/src/main.py", line 50, in getListings
    self.saveToJson(i)
  File "/opt/airflow/dags/src/main.py", line 58, in saveToJson
    with open(filename, 'w+') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'data/result_page_number_1_2023-07-28.json'
[2023-07-28T14:06:53.585+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=toronto_real_estate_etl, task_id=Extract, execution_date=20230728T140246, start_date=20230728T140248, end_date=20230728T140653
[2023-07-28T14:06:53.596+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 22 for task Extract ([Errno 2] No such file or directory: 'data/result_page_number_1_2023-07-28.json'; 5616)
[2023-07-28T14:06:53.617+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-28T14:06:53.635+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
