[2023-09-01T11:18:39.309+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: toronto_real_estate_etl.Extract manual__2023-09-01T11:18:38.418341+00:00 [queued]>
[2023-09-01T11:18:39.315+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: toronto_real_estate_etl.Extract manual__2023-09-01T11:18:38.418341+00:00 [queued]>
[2023-09-01T11:18:39.315+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-09-01T11:18:39.325+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): Extract> on 2023-09-01 11:18:38.418341+00:00
[2023-09-01T11:18:39.329+0000] {standard_task_runner.py:57} INFO - Started process 552 to run task
[2023-09-01T11:18:39.332+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'toronto_real_estate_etl', 'Extract', 'manual__2023-09-01T11:18:38.418341+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpx9ca4ne1']
[2023-09-01T11:18:39.333+0000] {standard_task_runner.py:85} INFO - Job 125: Subtask Extract
[2023-09-01T11:18:39.365+0000] {task_command.py:410} INFO - Running <TaskInstance: toronto_real_estate_etl.Extract manual__2023-09-01T11:18:38.418341+00:00 [running]> on host e5187b3c4256
[2023-09-01T11:18:39.417+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='toronto_real_estate_etl' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2023-09-01T11:18:38.418341+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-01T11:18:38.418341+00:00'
[2023-09-01T11:18:39.418+0000] {logging_mixin.py:150} INFO - 2023-09-01
[2023-09-01T11:18:39.418+0000] {logging_mixin.py:150} INFO - toronto_url https://www.kijiji.ca/b-apartments-condos/city-of-toronto/c37l1700273
[2023-09-01T11:18:39.418+0000] {Extract.py:37} INFO - https://www.kijiji.ca/b-apartments-condos/page-1/c37l1700273
[2023-09-01T11:18:42.010+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/main.py", line 32, in extract
    e.getListings(2,str(date))
  File "/opt/airflow/dags/src/Extract.py", line 60, in getListings
    self.saveToJson(i,run_date)
  File "/opt/airflow/dags/src/Extract.py", line 66, in saveToJson
    os.makedirs('/opt/airflow/dags/data/'+run_date)
  File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/opt/airflow/dags/data/2023-09-01'
[2023-09-01T11:18:42.017+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=toronto_real_estate_etl, task_id=Extract, execution_date=20230901T111838, start_date=20230901T111839, end_date=20230901T111842
[2023-09-01T11:18:42.028+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 125 for task Extract ([Errno 17] File exists: '/opt/airflow/dags/data/2023-09-01'; 552)
[2023-09-01T11:18:42.038+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-09-01T11:18:42.058+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
